2020-08-12 17:56:20,432 INFO    MainThread:8600 [wandb_init.py:_log_setup():255] Logging user logs to .\wandb\runs\run-20200812_175620-1h0e4gys\logs\debug-20200812_175620-1h0e4gys.log
2020-08-12 17:56:20,433 INFO    MainThread:8600 [wandb_init.py:_log_setup():256] Logging internal logs to .\wandb\runs\run-20200812_175620-1h0e4gys\logs\debug-internal-20200812_175620-1h0e4gys.log
2020-08-12 17:56:20,433 INFO    MainThread:8600 [wandb_setup.py:_flush():68] setting env: {}
2020-08-12 17:56:20,433 INFO    MainThread:8600 [wandb_setup.py:_flush():68] multiprocessing start_methods=spawn
2020-08-12 17:56:20,435 WARNING MainThread:8600 [wandb_setup.py:__init__():214] Ignoring settings passed to wandb.setup() which has already been configured.
2020-08-12 17:56:29,952 INFO    MainThread:8600 [wandb_run.py:_console_start():772] atexit reg
2020-08-12 17:56:29,952 INFO    MainThread:8600 [wandb_run.py:_redirect():687] redirect: off
2020-08-12 17:56:29,953 INFO    MainThread:8600 [wandb_config.py:__setitem__():93] config set magic = {'enable': True} - <bound method RunManaged._config_callback of <wandb.sdk.wandb_run.RunManaged object at 0x000001E4690BAEF0>>
2020-08-12 17:56:29,953 INFO    MainThread:8600 [wandb_run.py:_config_callback():296] config_cb magic {'enable': True} {'_wandb': {'cli_version': '0.0.40'}, 'magic': {'enable': True}}
2020-08-12 17:56:29,953 INFO    MainThread:8600 [wandb_run.py:_config_callback():296] config_cb None None {'_wandb': {'cli_version': '0.0.40'}, 'magic': {'enable': True}}
2020-08-12 17:56:36,096 INFO    MainThread:8600 [wandb_run.py:_atexit_cleanup():761] got exitcode: 0
2020-08-12 17:56:36,097 INFO    MainThread:8600 [wandb_run.py:_restore():733] restore
2020-08-12 17:56:38,689 INFO    MainThread:8600 [internal.py:handle_exit():49] Process exited cleanly
